spring.application.name=cs_2025_56
spring.datasource.url=jdbc:mysql://localhost:3306/user_db?serverTimezone=GMT%2B8
spring.datasource.username=root
spring.datasource.password=zzh00
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
server.port=8080

# MyBatis配置
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.cat.entity